### ISSUE TITLE
Not able to build screen-shots - chrome

### ISSUE THREAD

**Issue by svx** [plone/papyrus#110]
Running:

```
make screenshots-chrome
```

is failing and giving errors.

" Interesting " enough it seems that it has to do with the docs about plone.app.robotframework

![pap-fail1](https://cloud.githubusercontent.com/assets/358860/17744572/96cf8dee-64a8-11e6-93e1-9f42feba2494.png)
![pap-fail2](https://cloud.githubusercontent.com/assets/358860/17744571/96c9178e-64a8-11e6-9526-d7862c31f5f0.png)

@polyester would you mind to have a look ? I was in the process of pushing a new version of the docs.

**Comment by polyester** [comment]
oh damn. That's the 'supposed to break' section of the plone.app.robotframework docs, actually more tests than docs. I thought I had excluded them all from being run by adding
    Force Tags  wip-not_in_docs
, but will look later/tomorrow if their docs were updated and the tag not applied to all codeblocks in happy.rst.

If in a pinch for time: remove happy.rst, run make screenshots-chrome, then git-pull happy.rst back in again and run make html.

**Comment by svx** [comment]
I will wait, hopefully this will be resolved soon, tonight/tomorrow is completely fine :) If will take longer please, let me know so that I can think about a work around :)

**Comment by polyester** [comment]
probably the best is to say that for "make screenshots-chrome (and -firefox and -friends" the whole `*/plone.app.robotframework/*` should be an exclude pattern when calling sphinx. That makes more sense than tagging all tests in their docs with special tags, which is brittle if their docs are updated.

**Comment by svx** [comment]
It would be cool, if we would be able to set sich stuff in the conf.py, for example like this:

``` python
if tags.has('robotscreen'):
    exclude_patterns = ['external/plone.app.robotframework/*']
```

with that, you could use

```
$(SPHINXBUILD) -t robotscreen
```

But since we are using pybot I have no clue how to integrate that .

**Comment by polyester** [comment]
solved. Mysterious spacing issue in happy.rst made it so that the tags weren't read. Pushed to plone.app.robotframework so pulling that to newest should fix.

Works here now, will leave issue open until works on other people's machines as well. 

And yes, more flexible exclusion would be nice, but it seems pybot does not have many options for that.

**Comment by svx** [comment]
OK, working here on Ubuntu 14, 16 and Fedora 24.

Is there maybe a way that we could use a custom sphinx builder to call pybot ?

On the other hand I am really not sure how much time it is worth to spend on fixing papyrus 1, I would prefer to write that down as a note and spend more time on actually developing papyrus 2, so that we can get rid of version 1 at some point and move to a improved one.

In order to do so, a planning sprint would be nice.

**Comment by svx** [comment]
closing this
