### ISSUE TITLE
Robotframework is failing if :ref: commands are used in the docs

### ISSUE THREAD

**Issue by MrTango** [plone/papyrus#129]
You can see this currently in the adding-folders.rst which fails because of this line:

```
-  *Settings,* for allowing comments about the item, enabling :ref:`rst_prev-next-links`,
   and choosing whether it shows in the navigation menu for the web
   site.
```

**Comment by MrTango** [comment]
@datakurre could it be that this is related to sphinxcontrib-robotframework?
Do you have any hints how to solve this?

**Comment by datakurre** [comment]
Are there any more detailed errors or stacktraces? Currently I can only guess that the issue is that robot environment does not have required robot extensions.

**Comment by MrTango** [comment]
That is what i get if i run this robot test to generate a screen shot:

```
$ ./bin/robot source/documentation/working-with-content/adding-content/adding-folders.rst
[ ERROR ] Parsing 'source/documentation/working-with-content/adding-content/adding-folders.rst' failed: ValueError: need more than 0 values to unpack

Try --help for usage information.
```

other robot tests generating scren shots are working and it is definitely the :ref: part which is breaking it.

**Comment by datakurre** [comment]
@MrTango Thanks. I believe this is because of ``./bin/robot`` not having the same docutils environment with Sphinx. So, most probably screenshot-generation in sphinx-build still works normally. Just executing the docs "as tests" with robot framework fails.

I'll look this during weekend. Probably I can make bin/robot to load Sphinx-packages so that docutils behaves similarly.

**Comment by MrTango** [comment]
No it does not, thats why i run this robot manually.
You can see that in the officially docs the screen shoots for add folders are missing.
http://docs.plone.org/working-with-content/adding-content/adding-folders.html

**Comment by datakurre** [comment]
@MrTango I'll release plone.app.robotframeowrk 1.0.2 soon, which will fix this issue.

**Comment by MrTango** [comment]
Thank your very much Asko.
I'll try it out in a view days.
