### ISSUE TITLE
Missing arrows to browse docs with external includes

### ISSUE THREAD

**Issue by svx** [plone/papyrus#36]
If I include external docs via our setup and the external docs have more pages, I miss the arrows in the footer to browse all the docs.

**Comment by polyester** [comment]
Could you give an example? For instance when I go to http://docs.plone.org/external/plone.app.dexterity/docs/custom-views.html there's arrows in the footer.

**Comment by svx** [comment]
Oh sorry my bad ! I forgot to close the ticket. I already fixed that for the last docs release, the reason was a badly formated .rst file
