### ISSUE TITLE
todo: Plone 5 change loactions of includes

### ISSUE THREAD

**Issue by svx** [plone/papyrus#40]
- Change the structure of external includes, /external is fine for external stuff like pfg, but change this for example for mb.bob, meaning fetch them and put them not under external but straight to the right place in the docs, do the same for exmaple later on with cmf stuff.

reason: to avoid urls, with external in it, like api, cmf and so on.

the idea so far is start with that from Plone 5 on, with doing that we wil not mess up search and seo for Plone 3 and Plone 4 docs.

**Comment by svx** [comment]
We have to rethink, our current includes from external docs, our current setup works fine for 'non core' docs, since they go into /external but this implementation is not great for 'core docs'. 
I want to put 'core docs' not under /external but where they belong, like for example /develop/addons/bobtemplates.
Further and this is not an issue here, but in some 'core add-ons', we have to make sure that they follow http://docs.plone.org/about/documentation_styleguide_addons.html#id2, which is not the case yet, with for example: https://github.com/plone/bobtemplates.plone

**Comment by polyester** [comment]
There's no *structural* reason we're putting external docs under /external, it just makes it clear that these are not to be found in the repo, and need to be edited elsewhere. But if it's a 'core' add-on, it for sure can be included directly in the right place.

But: I would make it a **condition** then that the add-on follows the styleguide. This is not a nice-to-have, but a condition.

**Comment by svx** [comment]
Yes, that is exatly what we have with for example bobtemplates, that is why I opened: https://github.com/plone/bobtemplates.plone/issues/34

**Comment by svx** [comment]
ok ! will close that now, everything is clear and sorted out
