### ISSUE TITLE
spell check is broken 

### ISSUE THREAD

**Issue by svx** [plone/papyrus#41]
spell check is not working anymore, even better which each run I get different results on a file which is not changed at all.
also the makefile is giving errors ....

**Comment by polyester** [comment]
I think it has more to do with 
https://github.com/plone/papyrus/commit/0b72621b4ba1d9669a6dc7556f26734fc1a58132

**Comment by polyester** [comment]
Yep, just checked, putting it back in documentation makes it work again.
