### ISSUE TITLE
Change html build to dirhtml ?

### ISSUE THREAD

**Issue by svx** [plone/papyrus#43]
From the man page:

dirhtml:
- Build HTML pages, but with a single directory per document. Makes for prettier URLs (no .html) if served from a webserver

**Comment by polyester** [comment]
Hmmm, I don't like it very much

- some ugly URL's will arise (starting with # is a bit harsh) if you use TOC's up to header-level (like we do)
- local browsing (without webserver that makes the magic "index.html is default file in a directory" switcheroo that is required for this to work) is broken
- breaks the 'one rst becomes one html' rule in my head

but hey, I'm a traditionalist...

**Comment by svx** [comment]
Yeah I am also not sure, I just came is across during research about better testing of docs and jenkins, I will try it out on a test setup and will see what it does in rl ...

**Comment by svx** [comment]
ok I just tested and I say we stick to what we use already, closing this
