### ISSUE TITLE
add sphinxcontrib-findanything?

### ISSUE THREAD

**Issue by polyester** [plone/papyrus#44]
adding 'sphinxcontrib-findanything' to the eggs in buildout.cfg and enabling it in conf/conf.py gives you a rather wonderful, "just start typing" way to search for content. 

We'd need to document it, and it may need some CSS love, but it does work very well. Would this be a good idea? I like it.

**Comment by svx** [comment]
UH I will try just a couple of minutes !

**Comment by svx** [comment]
This is oot only partly working on a quick test build -  I guess this needs a bit more research

**Comment by svx** [comment]
on another note, I really would like to use solr for search, the build in search is quite limited

**Comment by svx** [comment]
Hm .. just testing on master docs build, I added the egg to buildout, run buildout and to the conf, but at least here it is doing *nothing* do I have to do more ?

**Comment by svx** [comment]
correction is is working under chrome but not with firefox at least not on my machine [yet] ?

**Comment by svx** [comment]
gosh .. correction again, now its working with firefox, but .. wow ... the documentation of this add-on is bad .....

**Comment by svx** [comment]
I changed the font size to 120, but still we have problems with long parts [see image]

![findeverything_pd](https://cloud.githubusercontent.com/assets/358860/7429857/988c85f2-f009-11e4-9d1d-426700365c2b.png)

The other thing is, could it confuse visitors if the click per accident on the page and the search box will pop up ?

**Comment by svx** [comment]
@polyester do you still want to include this in the next release or at all ?

**Comment by polyester** [comment]
not in next release; maybe later. I do think it's nice, but should be called up by a hotkey and not just pressing any key.

**Comment by svx** [comment]
@polyester Can I close this ?

**Comment by svx** [comment]
Closing this now, we have now algolia, which you can use with a hotkey
