### ISSUE TITLE
Use sphinxcontrib-images

### ISSUE THREAD

**Issue by svx** [plone/papyrus#48]
For certain images this could be useful, example is here: https://youtu.be/TGtGhbH2hcw

**Comment by svx** [comment]
ping ! any comments ? people think that could be useful ?

**Comment by polyester** [comment]
Haven't had time to check it; it's worth checking for a11y compliance. Can try tomorrow

**Comment by svx** [comment]
Just tested more, and yes, it is nice, bit it will not work with latex/pdf, so this is a no go
