### ISSUE TITLE
Use sphinxcontrib-plantuml to include UML-diagramms for Documentation

### ISSUE THREAD

**Issue by loechel** [plone/papyrus#53]
Might it be possible or considerable to include UMl-Diagrams in the Documentation?

For example I would like to have all Plone Workflows documented as UML State Machine Diagrams and willing to write them. But I think it should be done in a straightforward way of writing docs. PlantUML seems to be a possible solution for that.

Any thought on that?

**Comment by svx** [comment]
Hm .. reading the docs about plantuml, that would mean we have to add java as dependency of papyrus. do we think that is worth doing it ?

I am personally not really a huge fan of installing that in my build server, but if people think that is useful and we will use for more than one or two uml diagrams I may consider that :)

I guess if we only use a couple of diagrams it would be easier to make them local and upload as png ?

**Comment by gforcada** [comment]
What about graphviz? See http://sphinx-doc.org/ext/graphviz.html

**Comment by loechel** [comment]
Well PlantUML seems to depend on Graphviz. A Graphviz Support would also be welcome, but it did not Support you on writing UML Graphs.

There seems to be a PlantUML Remote Service avaliable (http://plantuml.sourceforge.net/server.html; http://www.plantuml.com/plantuml/), so that we do not need to install PlantUML on the build server but might allow them to request the rendered image from that remote servers. I am not sure ift the Sphinx modul could directly work together with the python modul: https://pypi.python.org/pypi/plantuml/ which just uses the remote server.  

@svx if it is just a http request which generates the UML and no Java Installation on the build Server, would that be ok for you?

**Comment by svx** [comment]
I say we discus that over sake next week :)

**Comment by svx** [comment]
Would be 'just'garphviz enough, seems like training docs are using that and it works good ?

**Comment by loechel** [comment]
Well graphviz did not have UML diagramms in it commen set, but having graphviz for diagramms would be a good enhancement in the meanwile. 
We could discuss the more elaburated plantuml on one of the next sprints.

**Comment by svx** [comment]
@loechel as in checking the current docs, we never needed UML diagrams, would you mind if I close this issue ? Feel free to re-open if you have a need/use case ?
