### ISSUE TITLE
Check new mr.developer functions

### ISSUE THREAD

**Issue by svx** [plone/papyrus#54]
Like here:

http://gil.badall.net/2015/05/23/fast-clones-for-faster-ci/

This could be handy for us, to speed up and for disk space

**Comment by gforcada** [comment]
Wait for it, it's completely broken ... I just tried it ... but yeah, at some point it should work and it should be used :) There's already a  pull request for it, hopefully fixing the error.

**Comment by svx** [comment]
same as #55 so I will close this one here
