### ISSUE TITLE
sparse vs --depth?

### ISSUE THREAD

**Issue by gforcada** [plone/papyrus#56]
I was reading issue #55 and this sparse thingie came across.

As I [understand sparse](http://briancoyner.github.io/blog/2013/06/05/git-sparse-checkout) is a way to only get a folder/subtree of a git repository right? If the only reason to do so is for bandwidth, why not use [--depth 1](http://stackoverflow.com/questions/6941889/is-git-clone-depth-1-shallow-clone-more-useful-than-it-makes-out)?

Note thought, that if you don't want to use the default branch (i.e usually master) you need to also specify your desired branch upon cloning (i.e. ``git clone REPO --depth 1 -b BRANCH``)

**Comment by polyester** [comment]
No, the reason is **not** bandwidth. The reason is we don't want code in a docs repository. It messes up the translation mechanism, it is confusing to non-programmers and is not necessary.

We're already using --depth 1 also. That is for bandwidth/diskspace saving, but not a replacement for sparse.

**Comment by gforcada** [comment]
Cool, nice setup then.
