### ISSUE TITLE
Add disqus ?

### ISSUE THREAD

**Issue by svx** [plone/papyrus#64]
We are looking for some time know to add something for user feedback, there is also now:

https://sphinxcontrib-disqus.readthedocs.org/en/latest/index.html

The only down site that I can see is that this could get possible out of hand, the idea is to get feedback not have discussions under/in the docs.

Maybe it is worth to try it out and maybe there is a way to set it up/ use it in way that will work for us.

**Comment by polyester** [comment]
I think it will be more confusing than helpful. A big footer pointing people to https://community.plone.org/c/documentation will concentrate the feedback where more people see it.

**Comment by svx** [comment]
Not sure, there is also the still the idea to have something like a 'floating button' on the site that people can click and send 'feedback' straight away, personally I prefer that one, have this in the footer is IMHO less cool, because quite often ppl do not read to the end.

Also we should keep in mind not to ask to may steps for that, click a button, write send will work, I guess every extra step is just too much, not sure if discourse understands now sending _new_ items as mail.

**Comment by polyester** [comment]
yeah, button is also great. I just don't want discussions to be even more spread out.

**Comment by svx** [comment]
well that is why I wrote:

_The only down site that I can see is that this could get possible out of hand, the idea is to get feedback not have discussions under/in the docs._

_Maybe it is worth to try it out and maybe there is a way to set it up/ use it in way that will work for us._

**Comment by svx** [comment]
closing this, we will go for another solution
