### ISSUE TITLE
Support Sphinx rst and markdown in same build

### ISSUE THREAD

**Issue by svx** [plone/papyrus#74]
You can now suport rst and markdown in the same sphinx build/config, this is really handy since parts of our js docs are still in markdown.

You can use Markdown and reStructuredText in the same Sphinx project.

This is nice because:
- you do need to convert via pandoc and fix last rst issues from hand
- you can include native without any changes

Setup:

```
 pip install recommonmark
```

and in your conf.py

``` python

from recommonmark.parser import CommonMarkParser

source_parsers = {
    '.md': CommonMarkParser,
}

source_suffix = ['.rst', '.md']
```

**Comment by svx** [comment]
@polyester do you know if we still have some parts written in md ?

**Comment by svx** [comment]
@polyester ping !

**Comment by polyester** [comment]
not in the docs that we include. The md parts are in https://github.com/plone/mockup; they mix documentation with JS code.
It is somehow served up at http://plone.github.io/mockup/dev/, but I am unsure how, as https://github.com/plone/plone.github.io is probably a private repo (or at least I get a 404 when looking at that)

**Comment by svx** [comment]
Ok closing this for now
