### ISSUE TITLE
Include page that we can link to from CONTRIBUTING.rst in packages

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/papyrus#75]
See https://github.com/plone/buildout.coredev/pull/135
and more discussion here: https://github.com/plone/Products.CMFPlone/issues/1179
I am just opening this ticket to see if the docs team foresees any problems with this, or knows a better spot to put this page.

**Comment by polyester** [comment]
docs/guidelines.rst on Products.CMFPlone seems like  a perfectly valid place. It will then also automagically appear at docs.plone.org and thus be indexed by search engines

**Comment by mauritsvanrees** [comment]
I have merged the coredev request so there now is a page.
That was about an hour ago. I don't see the page here yet:
http://docs.plone.org/develop/coredev/docs/guidelines.html
I am not up to date on how this works. Is this updated automatically once a day? A manual job? Depending on some Jenkins test?
No hurry, just wondering. :-)

**Comment by polyester** [comment]
artisanal, handcrafted, locally sourced & totally slow-cooked. I'll do another update this weekend.

**Comment by mauritsvanrees** [comment]
Excellent.

**Comment by mauritsvanrees** [comment]
I see it is up. Thanks!
