### ISSUE TITLE
Make sure to follow relase process 

### ISSUE THREAD

**Issue by svx** [plone/papyrus#83]
The last release of the documentation to docs.plone.org [12 of December 2015]  is not finished.

In preparation and during a release please make sure to follow all steps: https://github.com/plone/papyrus/blob/5.0/docs/make_release.rst
## What is missing:
- stats about typos and links
- changelog: https://github.com/plone/documentation/issues/381

As mentioned in https://github.com/plone/papyrus/blob/5.0/docs/make_release.rst I was using a tool named mr.publisher(https://github.com/svx/mr.publisher) in combination with vagrant for testing, building and publishing the docs, to make sure to follow all the steps.
mr.publisher is not up to date anymore, because of all the changes in papyrus, otherwise mr.docs(https://github.com/tiramisusolutions/mr.docs)could be extended to do all the steps.

**Comment by polyester** [comment]
@svx, how were the stats for "number of typos" calculated? I cannot find info on that.

When I do cat build/spell/output.txt | awk '{print $2}' | sed s/(// | sed s/).*// | sort | uniq | wc -l

I get 2238 for Plone4, and 1228 for Plone5, which is nowhere near the numbers reported by you. Trying to find out if you used another metric.

**Comment by svx** [comment]
Well this has do to with the changes which got introduced with the new way papyrus works, I am talking about https://github.com/plone/papyrus/blob/5.0/assemble-docs.tpl.genshi.

This fetches now all the sources, but since a couple of them are not following [yet] the best practices about repo setups, like /docs and how to handle the readme, you are getting lots of 'false positives' for example:

```
grep -ir 'Reistadbakk' .
./external/plone.app.contenttypes/README.html:<li>Martin Opstad Reistadbakk
```

@martior, sorry that I use your name as an example but is was one of the first ones :), I will by you beer ! :)

This has here to do with:

https://github.com/plone/plone.app.contenttypes/blob/master/docs/README.rst

Further on, the 'new way' fetches a lot of repos which still have typos and lots of terms are not yet included into 'good known words'  :)

So it is a combination of lots of changes which got introduced in 'ngo style' [sorry I was not able to resist] without proper testing all the results and outcomes. :)

If you check 'from hand' you will see that we are on around 178 typos in the docs for Plone 5 [real typos] without false positives 

Not that bad, it was worse, but certainly we could do better :)

**Comment by polyester** [comment]
That does not explain the discrepancy in the Plone 4 stats to me, where there are almost double the amount of errors than in Plone 5, and somehow the number has grown ten times from May 2015 to current.

And yes, of course a lot are false positives, and they should be added to known-word-list, this procedure just makes it easier to find them. 

```
 cat build/spell/output.txt | awk '{print $2}' | sed s/(// | sed s/).*// | sort | uniq
```

gives a good list to work from, separating out the 'false positives' 

I just was looking for how the previous stats were generated. 'Hand-checked' is not a scalable, repeatable metric, so that would have to be changed.

**Comment by svx** [comment]
@polyester I did not checked Plone 4 docs.

And no, I don't do that that by hand, I just did that now for checking and to give you an idea about the nr. of real typos.
If you really thing I count them every time from hand, you do not know me at all ....

**Comment by polyester** [comment]
I didn't think you'd count them by hand, just trying to hunt down where these big differences come from. Could be diffs in OS or version of hunspell/aspell/whatever wordlists used. It would just be useful to get more exact metrics down.

I'll add a big bunch of words to the known wordlist a.s.a.p.

**Comment by polyester** [comment]
as a side note: should we be strict on using en_us or is en_uk also alright? A lot of the false positives are on "organization" (US spelling) vs. "organisation" (UK spelling), as example.

I'm neutral on the issue, anyway.

same goes for "color" and "colour", etc.

**Comment by svx** [comment]
I just checked Plone 4 docs, this has to do  with the same issues like on the Plone 5 branch, including readme and changelog, so yes, names of user will give errors.

For the rest it is not that bad around 70 real typos and the rest are 'false positive'

**Comment by svx** [comment]
closing this
