### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by svx** [plone/papyrus#92]
Update sphinx and pygments to latest versions

**Comment by svx** [comment]
@polyester 

As you can see in: https://github.com/plone/papyrus/commit/0b41dc6ff844283f6abb3da9f15a3b03949db655

I am busy with updating the versions, by doing this and testing I came this across:

![robot-screen-docs-fail](https://cloud.githubusercontent.com/assets/358860/13568763/cc249540-e463-11e5-8756-9a43e20c733b.png)

It seems besides that, robot screen shots are working with the new versions, since you know robot framework and I don't would you mind to look at the failing test ?

**Comment by polyester** [comment]
I'll check a bit later. It looks like it has nothing to do with either Sphinx or pygments, nor RobotFramework for that matter. It's probably a side-effect of using a later version of Plone, where the CSS is slightly changed and thus the selector needs to be adapted.

**Comment by polyester** [comment]
It will need a slight rewrite of the robot-test. This is actually **good**, by the way: it is Plone behavior that changed between 5.0 and 5.0.2, so it _should_ break. Enabling content rules now requires an explicit click which it didn't before, which should also be reflected in the docs.
I'll try to get them fixed tomorrow.

**Comment by svx** [comment]
@polyester since https://github.com/plone/documentation/issues/560 is fixed, yeah, I guess I can open a PR for https://github.com/plone/papyrus/commit/0b41dc6ff844283f6abb3da9f15a3b03949db655 ?

**Comment by polyester** [comment]
yes

**Comment by svx** [comment]
done and fixed with https://github.com/plone/papyrus/commit/85ad74d0832239e59a56f9450fd9e3eac295f083
