### ISSUE TITLE
Proposal: switch to pip install zc.buildout

### ISSUE THREAD

**Issue by svx** [plone/papyrus#97]
I want to propose that we get rid of the following:

```
$ pip install -r requirements.txt
$ python bootstrap-buildout.py --setuptools-version=18.3.1 --version=2.4.3
```

 and switch to:

```
$ pip install zc.buildout
$ bin/buildout
```

I just tested it and it works !

Improvement:
- less files
- less build steps
- less complex 
- cleaner repo

**Comment by polyester** [comment]
now tested about a 100 times. Shall we just do it?

**Comment by svx** [comment]
I will do it during the next days
