### ISSUE TITLE
Think about possible help to fix search

### ISSUE THREAD

**Issue by svx** [plone/papyrus#99]
We should think about asking people with more experience to help us solving our issue with search

**Comment by gforcada** [comment]
let solr/elasticsearch crawl the website and use that? :-)

**Comment by svx** [comment]
https://github.com/rtfd/readthedocs.org/tree/master/readthedocs/search

**Comment by svx** [comment]
Just came across: http://www.blevesearch.com/

would that be an idea ? Looks doable :)

**Comment by svx** [comment]
Ok I did a test, implementing a base search, without theming of the search site nad tweaking the results

![dpo-search-bleve-sphinx](https://cloud.githubusercontent.com/assets/358860/17965552/7193405a-6abd-11e6-8e5d-d0a572ed26ca.png)

Searching with bleve is fast :)

**Comment by svx** [comment]
OK we have an update, I got the docs successfully working with  Algolia [https://community.algolia.com/]

Here is a screen-shot
![screenshot from 2016-09-25 11-24-10](https://cloud.githubusercontent.com/assets/358860/18814450/22f98eee-8314-11e6-9cb9-6437e0ccad0c.png)

I did not style the search output, but we certainly could do that !

**Comment by svx** [comment]
done !
